sonar.projectKey=modul3-251511030
sonar.projectName=Modul 3 251511030 Salman Alfarisi Firdaus
sonar.sources=app, routes, resources
sonar.exclusions=vendor/**, storage/**, bootstrap/cache/**, public/build/**
sonar.sourceEncoding=UTF-8